version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Sal1harslan/AIRAVAT-PRO-1"

[[analyzers]]
name = "php"